[2016-03-29 09:39:01,466][140735216661248][ERROR][run.py][line:35] [func:getMail] [msg:存在不支持的自定义格式的命令参数! [command: ['\xe8\xbf\x90\xe7\xbb\xb4\xe9\x83\xa8|\xe5\xbc\xa0\xe4\xbf\x9d\xe6\xb8\x85|Tel', ' 15210312367|QQ', ' 414095993']]]
